apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: alterius/todoapp-backend:v1.0.6
          command:
          - gunicorn
          - --bind
          - ":8000"
          - todo_drf.wsgi:application
          ports:
            - containerPort: 8000
      initContainers:
        - name: todoapp-migrate
          image: alterius/todoapp-backend:v1.0.6
          command:
          - /bin/bash
          - -c
          - |
            python manage.py makemigrations frontend -v 3  &&
            python manage.py makemigrations api -v 3  &&
            python manage.py migrate