apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alt3rius/neural-translator.git
    targetRevision: HEAD
    path: todoapp
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true