apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: translator
  namespace: translator
spec:
  template:
    spec:
      containers:
      - image: alterius/neural-translator
        imagePullPolicy: Always
        command:
        - uvicorn
        - --host
        - "0.0.0.0"
        - main:app
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "4Gi"
            cpu: "1200m"

